# Generated by Django 5.0.3 on 2024-03-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Nome da loja'),
        ),
    ]
