# Generated by Django 5.0.3 on 2024-03-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug da loja para o redirecionamento, sera criado auto.'),
        ),
    ]
