# Generated by Django 5.0.3 on 2024-03-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemaddon',
            options={'managed': True, 'verbose_name': 'Order Item Addon', 'verbose_name_plural': 'Order Item Addons'},
        ),
        migrations.AlterModelTable(
            name='orderitemaddon',
            table='order_item_addons',
        ),
    ]
